### ISSUE TITLE
KeyError: 'financials'

### ISSUE THREAD

**Issue by osadewasser** [astro30/valinvest#1]

**Comment by astro30** [comment]
Hey, 

I fixed the issue due to external API changes

**Comment by astro30** [comment]
Thanks for opening this issue.
Just for reference, I quote your mail:
_

> Hi,
> 
> Just installed valinvest and am trying the aapl.fscore() example. When I run the code I get the following error:
> 
> File "xxxx", line 71, in _get_financial_statement
> df = pd.json_normalize(res["financials"])
> KeyError: 'financials'
> 
> There are a few more errors but this one looked most readable. I'm pretty new to programming so hopefully this is an easy one. Any help is appreciated

_
I fixed the bug which was due to external API changes (before API Key was not mandatory, now it is). I think this issue was a bit too complicated for a newcomer. 

I recommend some resources/ideas for your learning path:
- [freeCodeCamp](https://www.freecodecamp.org/) (Learn the basics, choose the Python certifications)
- [The Hitchhiker's Guide to Python](https://docs.python-guide.org/) (How to create a python package)
- Look for easy tagged issues on Github
- Build/help building something you like in Python

Cheers
